projects/urls.py
from django.urls import path,include,re_path
from django.conf.urls import url
from . views import *
from . import views


app_name="home"

urlpatterns = [
    path("", views.home, name="home"),
    path("projectadd", views.addproject, name="addproject"),
    path("projectadded", views.projectadded, name="projectadded"),
    path("projectapi", views.rest_api_project, name="projectapi"),
    path("taskapi", views.rest_api_task, name="taskapi"),
    url(r'^project/(?P<project_id>[a-zA-Z0-9 \'&-\_]+)', views.project, name='project'),
    url(r'^projectedit/(?P<project_id>[a-zA-Z0-9 \'&-\_]+)', views.projectedit, name='projectedit'),
    url(r'^project-(?P<project_id>[a-zA-Z0-9 \'&-\_]+)/task/(?P<task_id>[a-zA-Z0-9 \'&-\_]+)', views.task, name='task'),
    path("taskadd", views.taskadd, name="taskadd"),
    url(r'^taskedit/(?P<task_id>[a-zA-Z0-9 \'&-\_]+)', views.taskedit, name='taskedit'),
]

ufberProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("projects.urls"))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/models.py
from django.db import models
from datetime import date 

class Projects(models.Model):
    name=models.CharField(max_length=50)
    description=models.CharField(max_length=500)
    startdate=models.DateField(auto_now=True)
    enddate=models.DateField(auto_now=True)
    duration=models.IntegerField(null=True)
    photo = models.ImageField(upload_to='static',null=True)

    def __str__(self):
        return self.name
    
class Task(models.Model):
    name=models.CharField(max_length=50)
    project=models.IntegerField(null=True)
    description=models.CharField(max_length=500)
    startdate=models.DateField(auto_now=True)
    enddate=models.DateField(auto_now=True)
    duration=models.IntegerField(null=True)
    asign_to=models.CharField(max_length=500,null=True)
    project_name=models.CharField(max_length=50,null=True)

    def __str__(self):
        return self.name

projects/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import Projects,Task
import os
from rest_framework.response import Response
from django.conf import settings
from .serialzers import ProjectSerializer,TaskSerializer
from rest_framework.decorators import api_view
from django.http import JsonResponse
import requests
import json
from django.core.files.storage import FileSystemStorage

@api_view(["GET"])
def rest_api_project(request):
    all_project=Projects.objects.all()
    serializer=ProjectSerializer(all_project,many=True)
    return Response(serializer.data)
@api_view(["GET"])
def rest_api_task(request):
    all_task=Task.objects.all()
    serializer=TaskSerializer(all_task,many=True)
    return Response(serializer.data)

def home(request):
    SERVER=request.META["HTTP_HOST"]
    if SERVER=="127.0.0.1:8000":
        url="http://127.0.0.1:8000/projectapi"
    else:
        url="https://ufabertest.herokuapp.com/projectapi"
    r=requests.get(url)
    parm=r.json()
    
    return render(request,'home.html',{"parm":parm})
def addproject(request):
    return render(request,"addproject.html")

def projectadded(request):
    name=request.POST.get("name")
    description=request.POST.get("description")
    start_dat=request.POST.get("stdt")
    end_date=request.POST.get("enddt")
    duration=request.POST.get("days")
    print(duration,"durationdurationdurationduration")
    duration=int(duration)
    photo=request.FILES['photo']
    fs = FileSystemStorage()
    filename = fs.save(photo.name, photo)
    print(filename,"filenamefilenamefilenamefilenamefilename")
    uploaded_file_url = fs.url(filename)
    print(uploaded_file_url,"uploaded_file_urluploaded_file_urluploaded_file_urluploaded_file_url")
    Projects.objects.create(name=name,description=description,startdate=start_dat,enddate=end_date, photo=photo,duration=duration)
    return redirect("home:home")
def project(request,project_id):
    SERVER=request.META["HTTP_HOST"]
    if SERVER=="127.0.0.1:8000":
        url="http://127.0.0.1:8000/projectapi"
        url2="http://127.0.0.1:8000/taskapi"
    else:
        url="https://ufabertest.herokuapp.com/projectapi"
        url2="https://ufabertest.herokuapp.com/taskapi"
    r=requests.get(url)
    parm=r.json()

    
    r2=requests.get(url2)
    r2=r2.json()
    print(parm,"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm")
    project={}
    print(project_id)
    if len(parm) == 1:
        project=r.json()[0]
  
    else:    
        for i in parm:
            if i['id']==int(project_id):
                project["id"]=i['id']
                project["name"]=i['name']
                project["description"]=i['description']
                project["startdate"]=i['startdate']
                project["enddate"]=i['enddate']
                project["photo"]=i['photo']
                project["duration"]=i['duration']
    print(project,"LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL")

    task=[]
    # print(r2,"LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL")
    project_id=int(project_id)
   

    if len(r2) == 1:
        task=r2
    elif len(r2) == 1:
        task=[]
    else:
         
        for j in r2:
            if j['project']==project_id:
                task.append(dict(id=j["id"],name=j["name"],description=j["description"],startdate=j["startdate"],enddate=j["enddate"],asign_to=j["asign_to"],project=j["project"]))
                # task.append(dict(name=j["name"]))
                # task.append(dict(id=j["project"]))
                # task.append(dict(id=j["startdate"]))
                # task.append(dict(id=j["enddate"]))
                # task[j["id"]]["id"]=j["id"]
                # task[j["id"]]["project"]=j["project"]
                # task[j["id"]]["description"]=j["description"]
                # task[j["id"]]["startdate"]=j["startdate"]
                # task[j["id"]]["enddate"]=j["enddate"]
                # task[j["id"]]["asign_to"]=j["asign_to"]
                
    
    parm={"project":project,"task":task}
    print(task,"cccccccccccccccccccccccccccc")
    return render(request,"project.html",parm)
def projectedit(request,project_id):
    name=request.POST.get("name")
    description=request.POST.get("description")
    start_dat=request.POST.get("stdt")
    end_date=request.POST.get("enddt")
    duration=request.POST.get("days")
    print(duration,"durationdurationdurationduration")
    duration=int(duration)
    photo=request.FILES['photo']

    # fs = FileSystemStorage()
    # filename = fs.save(photo.name, photo)
    # print(filename,"filenamefilenamefilenamefilenamefilename")
    # uploaded_file_url = fs.url(filename)
    Projects.objects.filter(id=project_id).update(name=name,description=description,startdate=start_dat,enddate=end_date, photo=photo,duration=duration)

    return redirect("home:home")
def taskadd(request):
    name=request.POST.get("name")
    description=request.POST.get("description")
    start_dat=request.POST.get("stdt")
    end_date=request.POST.get("enddt")
    duration=request.POST.get("days")
    asign_to=request.POST.get("assign")
    project_id=request.POST.get("project")
    project_id=int(project_id)
    print(project_id)
    project_name=request.POST.get("project_name")
    
    Task.objects.create(name=name,description=description,startdate=start_dat,enddate=end_date,project=project_id,project_name=project_name, asign_to=asign_to,duration=duration)
    return redirect("home:project", project_id=project_id)
def task(request,project_id,task_id):
    SERVER=request.META["HTTP_HOST"]
    if SERVER=="127.0.0.1:8000":
        url2="http://127.0.0.1:8000/taskapi"
    else:
        url2="https://ufabertest.herokuapp.com/taskapi"
    r2=requests.get(url2)
    parm=r2.json()
    my_task={}
    print("hhhhhhhhhhhhhhhhhhh")
    if len(parm) == 1:
        my_task=r2.json()[0]
    else:    
        for i in parm:
            print(i['id']==int(task_id))
            if i['id']==int(task_id):
                my_task["id"]=i['id']
                my_task["name"]=i['name']
                my_task["description"]=i['description']
                my_task["startdate"]=i['startdate']
                my_task["enddate"]=i['enddate']
                my_task["duration"]=i['duration']
                my_task["project"]=i['project']

    return render(request,"task.html",{"task":my_task})
def taskedit(request,task_id):
    name=request.POST.get("name")
    description=request.POST.get("description")
    start_dat=request.POST.get("stdt")
    end_date=request.POST.get("enddt")
    duration=request.POST.get("days")
    asign_to=request.POST.get("assign")
    project_id=request.POST.get("project")
   
    project_id=int(project_id)

    Task.objects.update(name=name,description=description,startdate=start_dat,enddate=end_date, asign_to=asign_to,duration=duration)
    return redirect("home:project",project_id=project_id)   

templates/addproject.html
{% include "base.html" %}
{% block content %}
<div class="container">
<form action="{% url 'home:projectadded' %}"  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="exampleFormControlInput1">Project Name</label>
        <input type="text" name="name" placeholder="Enter Project name" required>
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Description</label>
        <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="3" required></textarea>
    </div>
    <div class="row">
    <div class="form-group">
        <label for="exampleFormControlInput1">Start Date</label>
        <input class="stdt"  name="stdt" type="date" placeholder="Enter Project name" required>
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">End Date</label>
        <input name="enddt" class="enddt" type="date" placeholder="Enter Project name" required>
    </div>
    <div class="form-group">

        <input name="days" class="days" type="hidden" placeholder="Enter Project name" required>
    </div>
   
    </div>
    <h2 id="numdays"></h2>
    <div class="form-group">
        <label for="exampleFormControlFile1">Upload A Avtar</label>
        <input type="file" name="photo" class="form-control-file" id="exampleFormControlFile1" required>
    </div>
    <button type="submit">Add Project</button>
</form>
</div>
<script>
$(".enddt").change(function(){
        stdt=$('.stdt').val()
        enddt=$(".enddt").val(); 
        if (stdt == ""){
        $(".enddt").val("");
        alert("Enter Start Date First")
        }else{
         
        const oneDay = 24 * 60 * 60 * 1000; // hours*minutes*seconds*milliseconds
        const firstDate = new Date(stdt);
        const secondDate = new Date(enddt);

        const diffDays = Math.round(Math.abs((firstDate - secondDate) / oneDay)); 
        $(".numdays").text("Duration"+diffDays+" Days");
        $(".days").val(diffDays);
        }
    })


</script>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>Ufaber</title>
 <link rel="shortcut icon" href="#" />
 <style>
  .container{
    margin-top: 100px;
  background-color: wheat
  }
</style>
  </head>
  <body>

    <nav class="navbar navbar-dark bg-dark">
     <a class="navbar-brand" href="{% url 'home:home'  %}">Ufaber Projects</a>
     <a class="navbar-brand" href="{% url 'home:addproject'  %}">Add A Project</a>
    </nav>

    {% block content %}
    
    {% endblock  %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>


 

</script>
</html>

templates/home.html
{% include "base.html" %}
{% block content %}
<div class="container">
  <div class="row">
{% for i in parm %}
        <div class="card-group">
        <div class="card border-primary mb-3" style="width: 18rem;">
            <img src="{{i.photo}}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">Name:{{i.name}}</h5>
              
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Start Date:{{i.startdate}}</li>
              <li class="list-group-item">End Date:{{i.enddate}}</li>
           <li class="list-group-item">Duration: {{i.duration}}</li>
           <p class="card-text">Description:{{i.description}}</p>
            </ul>
            <div class="card-body">
              <a href="{% url 'home:project' project_id=i.id %}" class="card-link">View Project</a>
              {% comment %} <a href="#" class="card-link">Another link</a> {% endcomment %}
            </div>
          </div>
          </div>




{% endfor %}
</div>
</div>

 {% endblock  %}

templates/project.html
{% include "base.html" %}
{% block content %}
<img src="{{project.photo}}" class="card-img-top" style="border-radius: 50%;  height: 200px; ">
<div class="container" >
  
    <div class="real" style="text-align: center;">
  
    <h1>Name:{{project.name}}</h1>
    <h3>Description:{{project.description}}</h3>
   
        <p>Start Date:{{project.startdate}}</p>
        <p>End Date:{{project.enddate}}</p>
    
        <p>Duration :{{project.duration}}</p>
        {% if task == "[]" %}
        <p>No Task Created</p>
        {% else %}
        <table class="table">
            
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Project</th>
                        <th scope="col">Start Date</th>
                        <th scope="col">End Date</th>
                        <th scope="col">Assigned To</th>
                        <th scope="col">View</th>
                       
        
                    </tr>
                </thead>
                <tbody>
                    {% for i in task %}
                    <tr>
                        <th>{{i.name}}</th>
                        <th>{{i.project}}</th>
                        <th>{{i.startdate}}</th>
                        <th>{{i.enddate}}</th>
                        <th>{{i.asign_to}}</th>
                        <th><a href="{% url 'home:task' project_id=i.project task_id=i.id %}" class="card-link">View</a></th>
                        
                    </tr>
                    {% endfor %}
                </tbody>
               
                
        </table>
        {% endif %}
        <button type="button" class="btn btn-primary btn1">Add Task</button>
        <button type="button" class="btn btn-warning btn2">Cencil</button>
        <br>
        <br>
        <br>
    
    
    
    <div class="addtask">

<form action="{% url 'home:taskadd'  %}"  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
    <div class="form-group">
        <label for="exampleFormControlInput1">Project Name</label>
        <input type="text" name="name" placeholder="Enter Project name"  required>
    </div>
    
    
    <div class="form-group">
        <label for="exampleFormControlInput1">Start Date</label>
        <input class="stdt"  name="stdt" type="date" placeholder="Enter Task Start Date"  required>
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">End Date</label>
        <input name="enddt" class="enddt" type="date" placeholder="Enter Task Start Date"  required>
    </div>
     <div class="form-group">
        {% comment %} <label for="nddt_task">Assign To</label> {% endcomment %}
        {% comment %} <input   type="text" placeholder="Enter Whome To Assign"  required> {% endcomment %}
        <select class="form-control" name="assign" id="exampleFormControlSelect1">
            <option value="sourabh">sourabh</option>
            <option value="ashutosh">ashutosh</option>
            <option value="gourab">gourab</option>
           
    </select>
    </div>
    </div>
    <div class="form-group">
       
        <input name="days" class="days" type="hidden" required>
    </div>
    <div class="form-group">
       
        <input name="project" value="{{project.id}}" type="hidden" required>
        <input name="project_name" value="{{project.name}}" type="hidden" required>
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Description</label>
         <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="1"  required></textarea>
    </div>
   
   
    
    <h2 class="numdays"></h2>
  
    <button class="btn btn-primary" type="submit">Add Task</button>
    </div>
</form>
  

  </div>
        






        
    </div>

 <a  class="edit_prjct btn btn-primary">Edit Project</a> 
 <a  class="cncl btn btn-warning">Cencil</a> 
   <div class="container"> 
 <div class="edit">

    <form action="{% url 'home:projectedit' project_id=project.id %}"  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="exampleFormControlInput1">Project Name</label>
        <input type="text" name="name" placeholder="Enter Project name"  value="{{project.name}}" required>
    </div>
    
    <div class="row">
    <div class="form-group">
        <label for="exampleFormControlInput1">Start Date</label>
        <input class="stdt"  name="stdt" type="date" placeholder="Enter Project name" value="{{project.startdate}}" required>
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">End Date</label>
        <input name="enddt" class="enddt" type="date" placeholder="Enter Project name" value="{{project.enddate}}" required>
    </div>
    <div class="form-group">
       
        <input name="days" class="days" type="hidden" placeholder="Enter Project name" value="{{project.duration}}" required>
    </div>
    <h2 class="numdays"></h2>
     </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Description</label>
        <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="3"  required>{{project.description}}</textarea>
    </div>
   
   
    
    <div class="form-group">
        <label for="exampleFormControlFile1">Example file input</label>
        <input type="file" name="photo" class="form-control-file" id="exampleFormControlFile1" required>
    </div>
    <button type="submit">Add Project</button>
</form>
  
  
    </div>

</div>
</div> 

<script>

$(document).ready(function(){
    $(".edit").hide();
    $(".real").show();
    $(".cncl").hide()
    $(".addtask").hide()
    $(".btn2").hide()
    
    $(".edit_prjct").click(function () {
        $(".edit").show();
        $(".real").hide(); 
        $(".cncl").show()
        $(".edit_prjct").hide()
    })
    $(".cncl").click(function () {
        $(".edit").hide();
        $(".real").show();
        $(".cncl").hide() ;
        $(".edit_prjct").show()

    })
    $(".btn1").click(function () {
       
        $(".btn2").show();
        $(".btn1").hide() ;
        $(".addtask").show()
        

    })
    $(".btn2").click(function () {
       
        $(".btn1").show();
        $(".btn2").hide() ;
        $(".addtask").hide()
        

    })
    $(".enddt").change(function(){

            stdt=$('.stdt').val()
            enddt=$(".enddt").val(); 
            if (stdt == ""){
            $(".enddt").val("");
            alert("Enter Start Date First")
            }else{
             
            const oneDay = 24 * 60 * 60 * 1000; // hours*minutes*seconds*milliseconds
            const firstDate = new Date(stdt);
            const secondDate = new Date(enddt);
    
            const diffDays = Math.round(Math.abs((firstDate - secondDate) / oneDay)); 
            $(".numdays").text("Duration"+diffDays+" Days");
            $(".days").val(diffDays);
            }
        })




})
</script>

{% endblock  %}

templates/task.html
{% include "base.html" %}
{% block content %}
<div class="real" style="text-align: center;">
  
    <h1>Name:{{task.name}}</h1>
    <h3>Description:{{task.description}}</h3>
   
        <p>Start Date:{{task.startdate}}</p>
        <p>End Date:{{task.enddate}}</p>
    
        <p>Duration :{{task.duration}} Days</p>
        <p>Assigned To :{{task.asign_to}} Days</p>
        
        <a  class="edit_prjct pull-right">Edit Project</a> 
        <a  class="cncl">Cencil</a> 
        <br>
        <br>
        <br>
</div>
<div class="container">
<div class="edit">

       <form action="{% url 'home:taskedit' task_id=task.id %}"  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="exampleFormControlInput1">Project Name</label>
        <input type="text" name="name" placeholder="Enter Project name"  value="{{task.name}}" required>
    </div>
    
    <div class="row">
    <div class="form-group">
        <label for="exampleFormControlInput1">Start Date</label>
        <input class="stdt"  name="stdt" type="date" placeholder="Enter Project name" value="{{task.startdate}}" required>
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">End Date</label>
        <input name="enddt" class="enddt" type="date" placeholder="Enter Project name" value="{{task.enddate}}" required>
    </div>
    <div class="form-group">
       
        <input name="days" class="days" type="hidden" placeholder="Enter Project name" value="{{task.duration}}" required>
    </div>
    <div class="form-group">
       
        <input name="project" class="days" type="hidden" placeholder="Enter Project name" value="{{task.project}}" required>
    </div>
    <h2 class="numdays"></h2>
     </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Description</label>
        <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="3"  required>{{task.description}}</textarea>
    </div>
   
   
     <div class="form-group">
        <label for="nddt_task">Assign To</label>
        {% comment %} <input   type="text" placeholder="Enter Whome To Assign"  required> {% endcomment %}
        <select class="form-control" name="assign" id="exampleFormControlSelect1">
            <option value="sourabh">sourabh</option>
            <option value="ashutosh">ashutosh</option>
            <option value="gourab">gourab</option>
           
    </select>
    </div>
    
    <button type="submit">Edit Task</button>
</form>
  
  
</div>
</div>
<script>
    $(document).ready(function(){
       
    $(".edit").hide();
    $(".real").show();
    $(".cncl").hide()
    $(".addtask").hide()
    $(".btn2").hide()
    
    $(".edit_prjct").click(function () {
        $(".edit").show();
        $(".real").hide(); 
        $(".cncl").show()
        $(".edit_prjct").hide()
    })
    $(".cncl").click(function () {
        $(".edit").hide();
        $(".real").show();
        $(".cncl").hide() ;
        $(".edit_prjct").show()

    })
})
</script>
{% endblock  %}